spring:
    data:                       # database properties
        mongodb:
            uri: mongodb+srv://journal:journalapp@journalapp.oqccv.mongodb.net/?retryWrites=true&w=majority&appName=journalapp
            database: notematedb
            auto-index-creation: true
    application:
        name: notemate
    devtools:
        add-properties: false
    output:                   # color logs property
        ansi:
            enabled: ALWAYS
    main:                     # banner off property
        banner-mode: off

logging:                        # logger properties
    level:
        org:
            springframework: WARN
            mongodb:
                driver: WARN

springdoc:                      # swagger properties
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /api-docs/ui